language: groovy
jdk:
- oraclejdk8
dist: trusty
sudo: false
branches:
  only:
  - master
  - 1.3.x
  - grails-jdk-upgrade
  - bs3-with-grails3
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish --stacktrace'
env:
  global:
  - secure: wozEsfpjew/4jWnPjDE17U4V3jAqrl4wp0kA11EwcxFl7lK0D1AkH/HT4z1rsjY1NS0xB2fQUPF3TXQvugzWdQSQYrbCuWInAHP1uJHwOSeSU6F4OevY2086Di6Y1mzXQTeImCfmyadBKcEcMYqBh76zC5any5INMr+pb0CqsvTz8IeX0Xt7Sv9765Wqa7jd4/0FAz8REC/pbAMdxub1zvOoYTvafewgap5aY6cT7WYGbmXUb1k2KY352MGyuQxEk/7OFROaMUgx5Skl9t0cip//8TcU2zlygwrw5nLvQKUF2TeNxtzS0cWc/I1Lc4rIvZ9rFKX9RVfKkKrUtriiThzjkKbs9wuRnz6w3411nTh1ju/l9UfqxNl+dRFImmDSfNjOuR54GLyzZT78L1rYlfDKlDKH3NFBStN7dAMLwsFxesNSrGUmcsUNMtSYsfMS1gET2ETNpV+hsQXhw9Zy4rBG981d6oq5Zc/ow/PAVUV9DTs+H96kkY/petW/shOcHbyqqFLAOf3IzrG7Em1GOnoMoTAI956ZBmgQTi4hqLf6qSQwZUuRqoR/6EDLB8QCYjGTNRPnNSyaH2I3ygOO/6kIdUwmLhi+crebYG7tqJjDvFBwUW0feOJ7dV4Yko2uFlCs8SGkIvni/pfWcFSRY2rUvvoreDMGWJi3lktgmFc=
  - secure: NnI3oe2iftMRgINDzRLG4j78+teeOw8aUSgqSGUDiMw9tOArYtI9hgrEbOZEOxGdNuOd4PUujdzuJIA3d12mQH74o1ko8nRpZ/glvPdUM75ZBQV0IScC6GBZjGATB/18RjnF3CrANJgL9O74Z0acsCuzQMiwdAnC0BvbXlf2Jnm84wLT5JmFahT4NITPZXjYfA4r2V5EtD15ue4wUsp+bqPYV9IkRAETOhzc01lG97JGdCEnVnjgkAMAPRjwv26juVWKN0sHU63g5P0OJjNbSnd8hXfJdAxq1DFkOyfXpTvmSRMTZq8Rtjs4Iwx38M72bGiLoCeI6UcnbfBO7ngUrBy4fy0fgoNtXc5HFfelrshm3aLTnUdVa86Tqc4jwfmOLPmP6KW+0hY/v2qzuEjoUm75W0lUvc9+NqfoXCEQkkmc4fqayYQXghYz/z5ZnTskTgf5QD+pvEQILHxaAXPFHojDNzEGcx+ML5k21lZT48qcnlR4PqoOD4L33TaQPcnkLK1rvLoZpntnoAQEfgTAZzpOKhrtbEZJSmJN20IWkFmFooI8IGp6oh2Pe5Q8RfyoIgU0u86Cll7B4FJJJM36Vrjez9uAQtHeGLKupSq8aVQqSoOf/1NmzsqIMMZzlmSdHIw2BiIh8CwoSjuCoJ76Fm4IgPQ4yR1uj9TXV2wTZVs=
